export const FETCH_PRODUCTS = "PRODUCT/FETCH_PRODUCTS";
export const SHOW_LOADER = "PRODUCT/SHOW_LOADER";
export const HIDE_LOADER = "PRODUCT/HIDE_LOADER";
export const FETCH_CATEGORIES = "PRODUCT/CATEGORIES";
export const CREATE_USER = "USER/CREATE_USER";
export const DELETE_USER = "USER/DELETE_USER";